Updated yml

diff --git a/.github/workflows/run.yaml b/.github/workflows/run.yaml
--- a/.github/workflows/run.yaml
+++ b/.github/workflows/run.yaml
@@ -36,11 +36,11 @@ jobs:
       - name: Run Smoke Tests
         run: npx cucumber-js --tags "@smoke" --fail-fast
 
-   # 7️⃣ Generate HTML report (fail gracefully)
-      - name: Generate HTML Report
-        run: |
-          echo "Generating HTML report..."
-          node report.js || echo "⚠️ report.js failed, skipping HTML report generation."
+  #  # 7️⃣ Generate HTML report (fail gracefully)
+  #     - name: Generate HTML Report
+  #       run: |
+  #         echo "Generating HTML report..."
+  #         node report.js || echo "⚠️ report.js failed, skipping HTML report generation."
 
       # 7️⃣ Upload reports as artifacts
       - name: Upload Reports
